Feature 1
mihrab34/Projects pull request #2
Opened 2019-08-16 17:26 UTC by Qoosim

2019-08-21 17:53 UTC, samgaco commented
### Hi @Qoosim and @mihrab34 :hand: 

### Good work so far :+1: the website is looking like the original one but there are some points to address:

* The **search icon** should be enclosed in button tags

* The **navigation bar** should have at least three embedded images on the rightmost part of the navbar that represents icons and/or an avatar
![icons7](https://user-images.githubusercontent.com/34820784/63454155-86d15300-c44a-11e9-8fec-4ccee9ccf820.png)

* The videos and the thumbnails should show the **number of views**.

* Read about [HTML semantic](https://www.w3schools.com/html/html5_semantic_elements.asp) elements and use them. You could use `<main>` tag for the dominant content of the body or `<footer>` for the footer.

* The description under the video is overflowing the subscribe button and the profile of the uploader. There are also some grey margins on both sides. You could try to correct these issues.
![Screenshot_2019-08-21_19-44-21](https://user-images.githubusercontent.com/34820784/63454974-1e837100-c44c-11e9-82b8-f559ec4f5d14.png)

### Please :pray: work on these points and submit back for another code review (remember to send for review the link to the pull request. Regards! :muscle:

2019-08-21 17:54 UTC, samgaco requested changes
### Hi @Qoosim and @mihrab34 :hand: 

### Good work so far :+1: the website is looking like the original one but there are some points to address:

* The **search icon** should be enclosed in button tags

* The **navigation bar** should have at least three embedded images on the rightmost part of the navbar that represents icons and/or an avatar
![icons7](https://user-images.githubusercontent.com/34820784/63454155-86d15300-c44a-11e9-8fec-4ccee9ccf820.png)

* The videos and the thumbnails should show the **number of views**.

* Read about [HTML semantic](https://www.w3schools.com/html/html5_semantic_elements.asp) elements and use them. You could use `<main>` tag for the dominant content of the body or `<footer>` for the footer.

* The description under the video is overflowing the subscribe button and the profile of the uploader. There are also some grey margins on both sides. You could try to correct these issues.
![Screenshot_2019-08-21_19-44-21](https://user-images.githubusercontent.com/34820784/63454974-1e837100-c44c-11e9-82b8-f559ec4f5d14.png)

### Please :pray: work on these points and submit back for another code review (remember to send for review the link to the pull request. Regards! :muscle:

2019-08-21 17:54 UTC, samgaco commented on index.html
> +        <a href="#"><span class="search-mirror"></span></a>
The search icon should be enclosed within `<button>` tags

2019-08-21 17:56 UTC, samgaco requested changes
And remember to get rid of the commented code in your project.

2019-08-21 17:56 UTC, samgaco commented on index.html
> +        <!-- <img src="image/search-icon.png" alt="Search-icon" title="Search" id="mirror"> -->
It's better not to have commented code :smiley:

2019-08-27 18:35 UTC, uche-inyama requested changes
Hi team, :hand: you did a good job,:handshake: You have  implemented the changes as requested. 

However, I want to make a suggestion, when you want to add icons next time, use [font awesome](https://fontawesome.com/) check it out here. 

However, there is still one more edit to make, your **README.md file** 

**First**, remove this:  :point_down: 
#### <<<<<<< HEAD This is our first collaborative project in Microverse.
#### This is our first collaborative project in Microverse  ff616738828fe544affa50214900e7fb184c3761  

 from your **README** 

Also, make your **README** more descriptive, by adding:
  - [ ] Live version of your project, use [GitHack](https://raw.githack.com/)
  - [ ] Write on how a vistor to your github account can clone the project.
  - [ ] For more detailed information for vistors, provide a link to Odin project.
  - [ ] The collaborators of the project, adding the links to your individual github accounts or any site that promotes your skill as a software developer.

 Update your README and submit another code review form.

#### Guys, you are almost there. :muscle:

2019-09-02 16:32 UTC, merged